title: BE KIND app
author: OVM SOFT
theme: minima
description: Kindness is a type of behavior marked by acts of generosity, consideration, or concern for others, without expecting praise or reward in return

minima:
  nav_pages:
    - /be-kind/issues.md
    - /be-kind/about.md
  
