title: Be KIND app
author: OVM SOFT
theme: minima
description: Kindness is a type of behavior marked by acts of generosity, consideration, or concern for others, without expecting praise or reward in return

# 2.5.2 (2024)
remote_theme: jekyll/minima@c6e74bb

header_pages:
    - issues.md
    - privacy.md
    - about.md
